pl-ai-classifier-db-prod             | 
pl-ai-classifier-db-prod             | PostgreSQL Database directory appears to contain a database; Skipping initialization
pl-ai-classifier-db-prod             | 
pl-ai-classifier-db-prod             | 2025-07-15 10:52:45.606 UTC [1] LOG:  starting PostgreSQL 15.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
pl-ai-classifier-db-prod             | 2025-07-15 10:52:45.611 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pl-ai-classifier-db-prod             | 2025-07-15 10:52:45.611 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pl-ai-classifier-db-prod             | 2025-07-15 10:52:45.614 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pl-ai-classifier-db-prod             | 2025-07-15 10:52:45.621 UTC [29] LOG:  database system was shut down at 2025-07-15 10:52:19 UTC
pl-ai-classifier-db-prod             | 2025-07-15 10:52:45.641 UTC [1] LOG:  database system is ready to accept connections
pl-ai-rag-db-prod                    | 
pl-ai-rag-db-prod                    | PostgreSQL Database directory appears to contain a database; Skipping initialization
pl-ai-rag-db-prod                    | 
pl-ai-rag-db-prod                    | 2025-07-15 10:52:46.348 UTC [1] LOG:  starting PostgreSQL 15.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
pl-ai-rag-db-prod                    | 2025-07-15 10:52:46.351 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pl-ai-rag-db-prod                    | 2025-07-15 10:52:46.351 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pl-ai-rag-db-prod                    | 2025-07-15 10:52:46.355 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pl-ai-rag-db-prod                    | 2025-07-15 10:52:46.363 UTC [29] LOG:  database system was shut down at 2025-07-15 10:52:19 UTC
pl-ai-rag-db-prod                    | 2025-07-15 10:52:46.385 UTC [1] LOG:  database system is ready to accept connections
pl-ai-analysis-db-prod               | 
pl-ai-analysis-db-prod               | PostgreSQL Database directory appears to contain a database; Skipping initialization
pl-ai-analysis-db-prod               | 
pl-ai-analysis-db-prod               | 2025-07-15 10:52:46.614 UTC [1] LOG:  starting PostgreSQL 15.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
pl-ai-analysis-db-prod               | 2025-07-15 10:52:46.614 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pl-ai-analysis-db-prod               | 2025-07-15 10:52:46.614 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pl-ai-analysis-db-prod               | 2025-07-15 10:52:46.621 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pl-ai-analysis-db-prod               | 2025-07-15 10:52:46.629 UTC [28] LOG:  database system was shut down at 2025-07-15 10:52:19 UTC
pl-ai-analysis-db-prod               | 2025-07-15 10:52:46.658 UTC [1] LOG:  database system is ready to accept connections
pl-ai-auth-db-prod                   | 
pl-ai-auth-db-prod                   | PostgreSQL Database directory appears to contain a database; Skipping initialization
pl-ai-auth-db-prod                   | 
pl-ai-user-db-prod                   | 
pl-ai-user-db-prod                   | PostgreSQL Database directory appears to contain a database; Skipping initialization
pl-ai-user-db-prod                   | 
pl-ai-auth-db-prod                   | 2025-07-15 10:52:47.879 UTC [1] LOG:  starting PostgreSQL 15.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
pl-ai-auth-db-prod                   | 2025-07-15 10:52:47.880 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pl-ai-auth-db-prod                   | 2025-07-15 10:52:47.880 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pl-ai-auth-db-prod                   | 2025-07-15 10:52:47.884 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pl-ai-auth-db-prod                   | 2025-07-15 10:52:47.897 UTC [28] LOG:  database system was shut down at 2025-07-15 10:52:18 UTC
pl-ai-auth-db-prod                   | 2025-07-15 10:52:47.973 UTC [1] LOG:  database system is ready to accept connections
pl-ai-user-db-prod                   | 2025-07-15 10:52:48.031 UTC [1] LOG:  starting PostgreSQL 15.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
pl-ai-user-db-prod                   | 2025-07-15 10:52:48.031 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pl-ai-user-db-prod                   | 2025-07-15 10:52:48.031 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pl-ai-user-db-prod                   | 2025-07-15 10:52:48.039 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pl-ai-user-db-prod                   | 2025-07-15 10:52:48.050 UTC [29] LOG:  database system was shut down at 2025-07-15 10:52:09 UTC
pl-ai-resource-db-prod               | 
pl-ai-resource-db-prod               | PostgreSQL Database directory appears to contain a database; Skipping initialization
pl-ai-resource-db-prod               | 
pl-ai-user-db-prod                   | 2025-07-15 10:52:48.069 UTC [1] LOG:  database system is ready to accept connections
pl-ai-resource-db-prod               | 2025-07-15 10:52:48.197 UTC [1] LOG:  starting PostgreSQL 15.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
pl-ai-resource-db-prod               | 2025-07-15 10:52:48.198 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pl-ai-resource-db-prod               | 2025-07-15 10:52:48.199 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pl-ai-resource-db-prod               | 2025-07-15 10:52:48.203 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pl-ai-resource-db-prod               | 2025-07-15 10:52:48.210 UTC [28] LOG:  database system was shut down at 2025-07-15 10:52:21 UTC
pl-ai-learning-db-prod               | 
pl-ai-learning-db-prod               | PostgreSQL Database directory appears to contain a database; Skipping initialization
pl-ai-learning-db-prod               | 
pl-ai-resource-db-prod               | 2025-07-15 10:52:48.240 UTC [1] LOG:  database system is ready to accept connections
pl-ai-image-generator-db-prod        | 
pl-ai-image-generator-db-prod        | PostgreSQL Database directory appears to contain a database; Skipping initialization
pl-ai-image-generator-db-prod        | 
pl-ai-learning-db-prod               | 2025-07-15 10:52:48.369 UTC [1] LOG:  starting PostgreSQL 15.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
pl-ai-learning-db-prod               | 2025-07-15 10:52:48.371 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pl-ai-learning-db-prod               | 2025-07-15 10:52:48.371 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pl-ai-learning-db-prod               | 2025-07-15 10:52:48.377 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pl-ai-learning-db-prod               | 2025-07-15 10:52:48.396 UTC [28] LOG:  database system was shut down at 2025-07-15 10:52:19 UTC
pl-ai-learning-db-prod               | 2025-07-15 10:52:48.418 UTC [1] LOG:  database system is ready to accept connections
pl-ai-image-generator-db-prod        | 2025-07-15 10:52:48.450 UTC [1] LOG:  starting PostgreSQL 15.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
pl-ai-image-generator-db-prod        | 2025-07-15 10:52:48.451 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pl-ai-image-generator-db-prod        | 2025-07-15 10:52:48.451 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pl-ai-image-generator-db-prod        | 2025-07-15 10:52:48.455 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pl-ai-image-generator-db-prod        | 2025-07-15 10:52:48.460 UTC [29] LOG:  database system was shut down at 2025-07-15 10:52:19 UTC
pl-ai-chatbot-db-prod                | 
pl-ai-chatbot-db-prod                | PostgreSQL Database directory appears to contain a database; Skipping initialization
pl-ai-chatbot-db-prod                | 
pl-ai-image-generator-db-prod        | 2025-07-15 10:52:48.473 UTC [1] LOG:  database system is ready to accept connections
pl-ai-chatbot-db-prod                | 2025-07-15 10:52:48.534 UTC [1] LOG:  starting PostgreSQL 15.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
pl-ai-chatbot-db-prod                | 2025-07-15 10:52:48.537 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
pl-ai-chatbot-db-prod                | 2025-07-15 10:52:48.539 UTC [1] LOG:  listening on IPv6 address "::", port 5432
pl-ai-chatbot-db-prod                | 2025-07-15 10:52:48.543 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
pl-ai-chatbot-db-prod                | 2025-07-15 10:52:48.550 UTC [29] LOG:  database system was shut down at 2025-07-15 10:52:10 UTC
pl-ai-chatbot-db-prod                | 2025-07-15 10:52:48.560 UTC [1] LOG:  database system is ready to accept connections
pl-ai-frontend-prod                  |  INFO  Accepting connections at http://localhost:3000
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:51.844553+00:00 [notice] <0.44.0> Application syslog exited with reason: stopped
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:51.851019+00:00 [notice] <0.230.0> Logging: switching to configured handler(s); following messages may not be visible in this log output
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:51.852181+00:00 [notice] <0.230.0> Logging: configured log handlers are now ACTIVE
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.103948+00:00 [info] <0.230.0> ra: starting system quorum_queues
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.104053+00:00 [info] <0.230.0> starting Ra system: quorum_queues in directory: /var/lib/rabbitmq/mnesia/rabbit@6a318f609a1e/quorum/rabbit@6a318f609a1e
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.184457+00:00 [info] <0.261.0> ra system 'quorum_queues' running pre init for 0 registered servers
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.194886+00:00 [info] <0.262.0> ra: meta data store initialised for system quorum_queues. 0 record(s) recovered
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.210626+00:00 [notice] <0.267.0> WAL: ra_log_wal init, open tbls: ra_log_open_mem_tables, closed tbls: ra_log_closed_mem_tables
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.220312+00:00 [info] <0.230.0> ra: starting system coordination
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.220381+00:00 [info] <0.230.0> starting Ra system: coordination in directory: /var/lib/rabbitmq/mnesia/rabbit@6a318f609a1e/coordination/rabbit@6a318f609a1e
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.221991+00:00 [info] <0.274.0> ra system 'coordination' running pre init for 0 registered servers
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.222891+00:00 [info] <0.275.0> ra: meta data store initialised for system coordination. 0 record(s) recovered
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.223210+00:00 [notice] <0.280.0> WAL: ra_coordination_log_wal init, open tbls: ra_coordination_log_open_mem_tables, closed tbls: ra_coordination_log_closed_mem_tables
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.226791+00:00 [info] <0.230.0> 
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.226791+00:00 [info] <0.230.0>  Starting RabbitMQ 3.12.14 on Erlang 25.3.2.15 [jit]
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.226791+00:00 [info] <0.230.0>  Copyright (c) 2007-2024 Broadcom Inc and/or its subsidiaries
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.226791+00:00 [info] <0.230.0>  Licensed under the MPL 2.0. Website: https://rabbitmq.com
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.226892+00:00 [error] <0.230.0> This release series has reached end of life and is no longer supported. Please visit https://rabbitmq.com/versions.html to learn more and upgrade
pl-ai-rabbitmq-prod                  | 
pl-ai-rabbitmq-prod                  |   ##  ##      RabbitMQ 3.12.14
pl-ai-rabbitmq-prod                  |   ##  ##
pl-ai-rabbitmq-prod                  |   ##########  Copyright (c) 2007-2024 Broadcom Inc and/or its subsidiaries
pl-ai-rabbitmq-prod                  |   ######  ##
pl-ai-rabbitmq-prod                  |   ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com
pl-ai-rabbitmq-prod                  | 
pl-ai-rabbitmq-prod                  |   Erlang:      25.3.2.15 [jit]
pl-ai-rabbitmq-prod                  |   TLS Library: OpenSSL - OpenSSL 3.1.7 3 Sep 2024
pl-ai-rabbitmq-prod                  |   Release series support status: out of support
pl-ai-rabbitmq-prod                  | 
pl-ai-rabbitmq-prod                  |   Doc guides:  https://rabbitmq.com/documentation.html
pl-ai-rabbitmq-prod                  |   Support:     https://rabbitmq.com/contact.html
pl-ai-rabbitmq-prod                  |   Tutorials:   https://rabbitmq.com/getstarted.html
pl-ai-rabbitmq-prod                  |   Monitoring:  https://rabbitmq.com/monitoring.html
pl-ai-rabbitmq-prod                  | 
pl-ai-rabbitmq-prod                  |   Logs: <stdout>
pl-ai-rabbitmq-prod                  | 
pl-ai-rabbitmq-prod                  |   Config file(s): /etc/rabbitmq/conf.d/10-defaults.conf
pl-ai-rabbitmq-prod                  | 
pl-ai-rabbitmq-prod                  |   Starting broker...2025-07-15 10:52:52.238778+00:00 [info] <0.230.0> 
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.238778+00:00 [info] <0.230.0>  node           : rabbit@6a318f609a1e
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.238778+00:00 [info] <0.230.0>  home dir       : /var/lib/rabbitmq
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.238778+00:00 [info] <0.230.0>  config file(s) : /etc/rabbitmq/conf.d/10-defaults.conf
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.238778+00:00 [info] <0.230.0>  cookie hash    : lmgwLCdtKs1Gu48nXdZ5rQ==
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.238778+00:00 [info] <0.230.0>  log(s)         : <stdout>
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:52.238778+00:00 [info] <0.230.0>  data dir       : /var/lib/rabbitmq/mnesia/rabbit@6a318f609a1e
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.529985+00:00 [info] <0.230.0> Running boot step pre_boot defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.530067+00:00 [info] <0.230.0> Running boot step rabbit_global_counters defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.531008+00:00 [info] <0.230.0> Running boot step rabbit_osiris_metrics defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.531157+00:00 [info] <0.230.0> Running boot step rabbit_core_metrics defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.531966+00:00 [info] <0.230.0> Running boot step rabbit_alarm defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.537225+00:00 [info] <0.299.0> Memory high watermark set to 1552 MiB (1627627520 bytes) of 3880 MiB (4069068800 bytes) total
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.540925+00:00 [info] <0.301.0> Enabling free disk space monitoring (disk free space: 20437991424, total memory: 4069068800)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.541000+00:00 [info] <0.301.0> Disk free limit set to 50MB
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.544415+00:00 [info] <0.230.0> Running boot step code_server_cache defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.544536+00:00 [info] <0.230.0> Running boot step file_handle_cache defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.544962+00:00 [info] <0.304.0> Limiting to approx 1048479 file handles (943629 sockets)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.545344+00:00 [info] <0.305.0> FHC read buffering: OFF
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.545428+00:00 [info] <0.305.0> FHC write buffering: ON
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.546845+00:00 [info] <0.230.0> Running boot step worker_pool defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.546974+00:00 [info] <0.282.0> Will use 2 processes for default worker pool
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.547053+00:00 [info] <0.282.0> Starting worker pool 'worker_pool' with 2 processes in it
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.548089+00:00 [info] <0.230.0> Running boot step database defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.549019+00:00 [info] <0.230.0> Node database directory at /var/lib/rabbitmq/mnesia/rabbit@6a318f609a1e is empty. Assuming we need to join an existing cluster or initialise from scratch...
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.549119+00:00 [info] <0.230.0> Configured peer discovery backend: rabbit_peer_discovery_classic_config
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.549239+00:00 [info] <0.230.0> Will try to lock with peer discovery backend rabbit_peer_discovery_classic_config
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.549580+00:00 [info] <0.230.0> All discovered existing cluster peers:
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.553909+00:00 [info] <0.230.0> Discovered no peer nodes to cluster with. Some discovery backends can filter nodes out based on a readiness criteria. Enabling debug logging might help troubleshoot.
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.556494+00:00 [notice] <0.44.0> Application mnesia exited with reason: stopped
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.646875+00:00 [info] <0.230.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.647060+00:00 [info] <0.230.0> Successfully synced tables from a peer
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.647495+00:00 [notice] <0.283.0> Feature flags: attempt to enable `stream_sac_coordinator_unblock_group`...
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.682666+00:00 [notice] <0.283.0> Feature flags: `stream_sac_coordinator_unblock_group` enabled
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.682859+00:00 [notice] <0.283.0> Feature flags: attempt to enable `restart_streams`...
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.719500+00:00 [notice] <0.283.0> Feature flags: `restart_streams` enabled
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.720382+00:00 [info] <0.230.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.720708+00:00 [info] <0.230.0> Successfully synced tables from a peer
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.725947+00:00 [info] <0.230.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.726194+00:00 [info] <0.230.0> Successfully synced tables from a peer
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.726343+00:00 [info] <0.230.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.726473+00:00 [info] <0.230.0> Will try to unlock with peer discovery backend rabbit_peer_discovery_classic_config
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.727521+00:00 [info] <0.230.0> Running boot step tracking_metadata_store defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.727668+00:00 [info] <0.480.0> Setting up a table for connection tracking on this node: tracked_connection
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.727731+00:00 [info] <0.480.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.728083+00:00 [info] <0.480.0> Setting up a table for per-user connection counting on this node: tracked_connection_per_user
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.728278+00:00 [info] <0.480.0> Setting up a table for channel tracking on this node: tracked_channel
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.728414+00:00 [info] <0.480.0> Setting up a table for channel tracking on this node: tracked_channel_per_user
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.728548+00:00 [info] <0.230.0> Running boot step networking_metadata_store defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.728946+00:00 [info] <0.230.0> Running boot step feature_flags defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.729138+00:00 [info] <0.230.0> Running boot step codec_correctness_check defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.729197+00:00 [info] <0.230.0> Running boot step external_infrastructure defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.729391+00:00 [info] <0.230.0> Running boot step rabbit_event defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.729939+00:00 [info] <0.230.0> Running boot step rabbit_registry defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.730026+00:00 [info] <0.230.0> Running boot step rabbit_auth_mechanism_amqplain defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.730296+00:00 [info] <0.230.0> Running boot step rabbit_auth_mechanism_cr_demo defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.730410+00:00 [info] <0.230.0> Running boot step rabbit_auth_mechanism_plain defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.730544+00:00 [info] <0.230.0> Running boot step rabbit_exchange_type_direct defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.730609+00:00 [info] <0.230.0> Running boot step rabbit_exchange_type_fanout defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.730645+00:00 [info] <0.230.0> Running boot step rabbit_exchange_type_headers defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.730692+00:00 [info] <0.230.0> Running boot step rabbit_exchange_type_topic defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.730756+00:00 [info] <0.230.0> Running boot step rabbit_mirror_queue_mode_all defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.730931+00:00 [info] <0.230.0> Running boot step rabbit_mirror_queue_mode_exactly defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.730980+00:00 [info] <0.230.0> Running boot step rabbit_mirror_queue_mode_nodes defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.731021+00:00 [info] <0.230.0> Running boot step rabbit_priority_queue defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.731196+00:00 [info] <0.230.0> Priority queues enabled, real BQ is rabbit_variable_queue
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.731255+00:00 [info] <0.230.0> Running boot step rabbit_queue_location_client_local defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.731322+00:00 [info] <0.230.0> Running boot step rabbit_queue_location_min_masters defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.731371+00:00 [info] <0.230.0> Running boot step rabbit_queue_location_random defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.734305+00:00 [info] <0.230.0> Running boot step kernel_ready defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.734488+00:00 [info] <0.230.0> Running boot step rabbit_sysmon_minder defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.735338+00:00 [info] <0.230.0> Running boot step rabbit_epmd_monitor defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.736680+00:00 [info] <0.488.0> epmd monitor knows us, inter-node communication (distribution) port: 25672
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.737138+00:00 [info] <0.230.0> Running boot step guid_generator defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.739228+00:00 [info] <0.230.0> Running boot step rabbit_node_monitor defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.739749+00:00 [info] <0.492.0> Starting rabbit_node_monitor (in ignore mode)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.740290+00:00 [info] <0.230.0> Running boot step delegate_sup defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.741074+00:00 [info] <0.230.0> Running boot step rabbit_memory_monitor defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.741605+00:00 [info] <0.230.0> Running boot step rabbit_fifo_dlx_sup defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.741728+00:00 [info] <0.230.0> Running boot step core_initialized defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.741803+00:00 [info] <0.230.0> Running boot step rabbit_channel_tracking_handler defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.742052+00:00 [info] <0.230.0> Running boot step rabbit_connection_tracking_handler defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.742238+00:00 [info] <0.230.0> Running boot step rabbit_definitions_hashing defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.742351+00:00 [info] <0.230.0> Running boot step rabbit_exchange_parameters defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.743063+00:00 [info] <0.230.0> Running boot step rabbit_mirror_queue_misc defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.743812+00:00 [info] <0.230.0> Running boot step rabbit_policies defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.744573+00:00 [info] <0.230.0> Running boot step rabbit_policy defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.744668+00:00 [info] <0.230.0> Running boot step rabbit_queue_location_validator defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.744983+00:00 [info] <0.230.0> Running boot step rabbit_quorum_memory_manager defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.745325+00:00 [info] <0.230.0> Running boot step rabbit_stream_coordinator defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.745894+00:00 [info] <0.230.0> Running boot step rabbit_vhost_limit defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.746022+00:00 [info] <0.230.0> Running boot step rabbit_mgmt_reset_handler defined by app rabbitmq_management
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.746320+00:00 [info] <0.230.0> Running boot step rabbit_mgmt_db_handler defined by app rabbitmq_management_agent
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.746594+00:00 [info] <0.230.0> Management plugin: using rates mode 'basic'
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.747389+00:00 [info] <0.230.0> Running boot step recovery defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.748526+00:00 [info] <0.230.0> Running boot step empty_db_check defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.748606+00:00 [info] <0.230.0> Will seed default virtual host and user...
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.749087+00:00 [info] <0.230.0> Adding vhost '/' (description: 'Default virtual host', tags: [])
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.751377+00:00 [info] <0.230.0> Inserted a virtual host record {vhost,<<"/">>,[],
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.751377+00:00 [info] <0.230.0>                                       #{description =>
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.751377+00:00 [info] <0.230.0>                                             <<"Default virtual host">>,
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.751377+00:00 [info] <0.230.0>                                         tags => []}}
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.764274+00:00 [info] <0.537.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@6a318f609a1e/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.765866+00:00 [info] <0.537.0> Setting segment_entry_count for vhost '/' with 0 queues to '2048'
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.769844+00:00 [info] <0.537.0> Starting message stores for vhost '/'
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.770302+00:00 [info] <0.547.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.772012+00:00 [info] <0.537.0> Started message store of type transient for vhost '/'
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.772401+00:00 [info] <0.551.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.773323+00:00 [warning] <0.551.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": rebuilding indices from scratch
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.774327+00:00 [info] <0.537.0> Started message store of type persistent for vhost '/'
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.774626+00:00 [info] <0.537.0> Recovering 0 queues of type rabbit_classic_queue took 7ms
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.774714+00:00 [info] <0.537.0> Recovering 0 queues of type rabbit_quorum_queue took 0ms
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.774777+00:00 [info] <0.537.0> Recovering 0 queues of type rabbit_stream_queue took 0ms
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.778553+00:00 [info] <0.230.0> Created user 'admin'
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.780193+00:00 [info] <0.230.0> Successfully set user tags for user 'admin' to [administrator]
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.781831+00:00 [info] <0.230.0> Successfully set permissions for user 'admin' in virtual host '/' to '.*', '.*', '.*'
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.781910+00:00 [info] <0.230.0> Running boot step rabbit_observer_cli defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.782664+00:00 [info] <0.230.0> Running boot step rabbit_looking_glass defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.782816+00:00 [info] <0.230.0> Running boot step rabbit_core_metrics_gc defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.783677+00:00 [info] <0.230.0> Running boot step background_gc defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.784180+00:00 [info] <0.230.0> Running boot step routing_ready defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.784251+00:00 [info] <0.230.0> Running boot step pre_flight defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.784613+00:00 [info] <0.230.0> Running boot step notify_cluster defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.784742+00:00 [info] <0.230.0> Running boot step networking defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.785198+00:00 [info] <0.230.0> Running boot step definition_import_worker_pool defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.785696+00:00 [info] <0.282.0> Starting worker pool 'definition_import_pool' with 2 processes in it
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.786758+00:00 [info] <0.230.0> Running boot step cluster_name defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.786900+00:00 [info] <0.230.0> Initialising internal cluster ID to 'rabbitmq-cluster-id-FEPPJE3HZ6QsPNDUNH2UFw'
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.788687+00:00 [info] <0.230.0> Running boot step direct_client defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.788909+00:00 [info] <0.230.0> Running boot step rabbit_maintenance_mode_state defined by app rabbit
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.789093+00:00 [info] <0.230.0> Creating table rabbit_node_maintenance_states for maintenance mode status
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.792645+00:00 [info] <0.230.0> Running boot step rabbit_management_load_definitions defined by app rabbitmq_management
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.792863+00:00 [info] <0.589.0> Resetting node maintenance status
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.809487+00:00 [info] <0.648.0> Management plugin: HTTP (non-TLS) listener started on port 15672
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.809990+00:00 [info] <0.676.0> Statistics database started.
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.810130+00:00 [info] <0.675.0> Starting worker pool 'management_worker_pool' with 3 processes in it
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.821780+00:00 [info] <0.690.0> Prometheus metrics: HTTP (non-TLS) listener started on port 15692
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.821988+00:00 [info] <0.589.0> Ready to start client connection listeners
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.824385+00:00 [info] <0.734.0> started TCP listener on [::]:5672
pl-ai-rabbitmq-prod                  |  completed with 4 plugins.
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.914886+00:00 [info] <0.589.0> Server startup complete; 4 plugins started.
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.914886+00:00 [info] <0.589.0>  * rabbitmq_prometheus
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.914886+00:00 [info] <0.589.0>  * rabbitmq_management
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.914886+00:00 [info] <0.589.0>  * rabbitmq_management_agent
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.914886+00:00 [info] <0.589.0>  * rabbitmq_web_dispatch
pl-ai-rabbitmq-prod                  | 2025-07-15 10:52:56.993896+00:00 [info] <0.9.0> Time to start RabbitMQ: 10346120 us
pl-ai-auth-service-prod              | DATABASE_URL: 
pl-ai-auth-service-prod              | Waiting for database at :...
pl-ai-auth-service-prod              | Skipping database check for now...
pl-ai-auth-service-prod              | Database is up!
pl-ai-auth-service-prod              | Applying database migrations...
pl-ai-image-generator-service-prod   | Waiting for Image Generator DB at image_generator_db:5432...
pl-ai-image-generator-service-prod   | Image Generator DB is up!
pl-ai-image-generator-service-prod   | Applying database migrations...
pl-ai-chatbot-service-prod           | Aspetto che il database sia pronto... (chatbot_db:5432)
pl-ai-chatbot-service-prod           | Database pronto!
pl-ai-image-generator-service-prod   | Operations to perform:
pl-ai-image-generator-service-prod   |   Apply all migrations: admin, auth, contenttypes, generator_api, sessions
pl-ai-image-generator-service-prod   | Running migrations:
pl-ai-image-generator-service-prod   |   No migrations to apply.
pl-ai-image-generator-service-prod   | Checking for secrets...
pl-ai-image-generator-service-prod   | Starting Django development server on port 8000...
pl-ai-auth-service-prod              | Operations to perform:
pl-ai-auth-service-prod              |   Apply all migrations: admin, auth, contenttypes, sessions, token_blacklist, users_api
pl-ai-auth-service-prod              | Running migrations:
pl-ai-auth-service-prod              |   No migrations to apply.
pl-ai-auth-service-prod              | Starting Django development server...
pl-ai-image-generator-service-prod   | Watching for file changes with StatReloader
pl-ai-image-generator-service-prod   | Performing system checks...
pl-ai-image-generator-service-prod   | 
pl-ai-chatbot-service-prod           | Operations to perform:
pl-ai-chatbot-service-prod           |   Apply all migrations: admin, auth, chatbot_api, contenttypes, sessions
pl-ai-chatbot-service-prod           | Running migrations:
pl-ai-chatbot-service-prod           |   No migrations to apply.
pl-ai-image-generator-service-prod   | System check identified no issues (0 silenced).
pl-ai-image-generator-service-prod   | July 15, 2025 - 10:53:26
pl-ai-image-generator-service-prod   | Django version 4.2.23, using settings 'service_config.settings'
pl-ai-image-generator-service-prod   | Starting development server at http://0.0.0.0:8000/
pl-ai-image-generator-service-prod   | Quit the server with CONTROL-C.
pl-ai-image-generator-service-prod   | 
pl-ai-auth-service-prod              | Watching for file changes with StatReloader
pl-ai-auth-service-prod              | Performing system checks...
pl-ai-auth-service-prod              | 
pl-ai-auth-service-prod              | System check identified no issues (0 silenced).
pl-ai-auth-service-prod              | July 15, 2025 - 10:53:28
pl-ai-auth-service-prod              | Django version 4.2.23, using settings 'service_auth.settings'
pl-ai-auth-service-prod              | Starting development server at http://0.0.0.0:8000/
pl-ai-auth-service-prod              | Quit the server with CONTROL-C.
pl-ai-auth-service-prod              | 
pl-ai-chatbot-service-prod           | Watching for file changes with StatReloader
pl-ai-chatbot-service-prod           | Performing system checks...
pl-ai-chatbot-service-prod           | 
pl-ai-chatbot-service-prod           | System check identified no issues (0 silenced).
pl-ai-chatbot-service-prod           | July 15, 2025 - 10:53:31
pl-ai-chatbot-service-prod           | Django version 4.2.23, using settings 'chatbot_service.settings'
pl-ai-chatbot-service-prod           | Starting development server at http://0.0.0.0:8000/
pl-ai-chatbot-service-prod           | Quit the server with CONTROL-C.
pl-ai-chatbot-service-prod           | 
pl-ai-resource-manager-service-prod  | Resource Manager Service Entrypoint (Web Process)
pl-ai-resource-manager-service-prod  | Waiting for Resource DB at resource_db:5432...
pl-ai-resource-manager-service-prod  | Resource DB is up!
pl-ai-resource-manager-service-prod  | Applying database migrations...
pl-ai-classifier-service-prod        | Image Classifier Service Entrypoint
pl-ai-classifier-service-prod        | Waiting for Classifier DB at classifier_db:5432...
pl-ai-classifier-service-prod        | Classifier DB is up!
pl-ai-classifier-service-prod        | Waiting for Broker at rabbitmq:5672...
pl-ai-classifier-service-prod        | Broker is up!
pl-ai-classifier-service-prod        | Applying database migrations...
pl-ai-resource-manager-service-prod  | Using separate DB variables: dbname=resource_db user=resource_user host=resource_db
pl-ai-learning-service-prod          | Waiting for database...
pl-ai-learning-service-prod          | Database connected!
pl-ai-learning-service-prod          | Running migrations...
pl-ai-rag-worker-prod                | Avviando Celery worker per RAG...
pl-ai-rag-worker-prod                | Aspettando RabbitMQ...
pl-ai-user-service-prod              | User Service Entrypoint
pl-ai-user-service-prod              | Waiting for User DB at user_db:5432...
pl-ai-user-service-prod              | User DB is up!
pl-ai-user-service-prod              | Applying database migrations...
pl-ai-rag-service-prod               | Avviando il servizio RAG web...
pl-ai-rag-service-prod               | Aspettando che il database sia pronto...
pl-ai-data-analysis-service-prod     | Data Analysis Service Entrypoint
pl-ai-data-analysis-service-prod     | Waiting for Analysis DB at analysis_db:5432...
pl-ai-data-analysis-service-prod     | Analysis DB is up!
pl-ai-data-analysis-service-prod     | Waiting for Broker at rabbitmq:5672...
pl-ai-data-analysis-service-prod     | Broker is up!
pl-ai-data-analysis-service-prod     | OpenAI secret found.
pl-ai-data-analysis-service-prod     | Applying database migrations...
pl-ai-rabbitmq-prod                  | 2025-07-15 10:53:55.269514+00:00 [info] <0.753.0> accepting AMQP connection <0.753.0> (172.25.0.21:43576 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:53:55.289395+00:00 [info] <0.753.0> connection <0.753.0> (172.25.0.21:43576 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-rabbitmq-prod                  | 2025-07-15 10:53:55.329963+00:00 [warning] <0.753.0> closing AMQP connection <0.753.0> (172.25.0.21:43576 -> 172.25.0.5:5672, vhost: '/', user: 'admin'):
pl-ai-rabbitmq-prod                  | 2025-07-15 10:53:55.329963+00:00 [warning] <0.753.0> client unexpectedly closed TCP connection
pl-ai-rag-worker-prod                | RabbitMQ pronto!
pl-ai-rag-worker-prod                | Verificando modello Sentence Transformers...
pl-ai-resource-manager-worker-prod   | Using separate DB variables: dbname=resource_db user=resource_user host=resource_db
pl-ai-resource-manager-service-prod  | Operations to perform:
pl-ai-resource-manager-service-prod  |   Apply all migrations: admin, auth, contenttypes, resources_api, sessions
pl-ai-resource-manager-service-prod  | Running migrations:
pl-ai-resource-manager-service-prod  |   No migrations to apply.
pl-ai-learning-service-prod          | OpenAI client inizializzato con successo
pl-ai-learning-service-prod          | No changes detected
pl-ai-resource-manager-service-prod  | Starting Django development server on port 8000...
pl-ai-rag-service-prod               | Database pronto!
pl-ai-rag-service-prod               | Aspettando RabbitMQ...
pl-ai-user-service-prod              | Operations to perform:
pl-ai-user-service-prod              |   Apply all migrations: admin, auth, contenttypes, sessions, user_api
pl-ai-user-service-prod              | Running migrations:
pl-ai-user-service-prod              |   No migrations to apply.
pl-ai-user-service-prod              | Starting Django development server on port 8000...
pl-ai-image-classifier-worker-prod   | 2025-07-15 10:54:05.259640: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
pl-ai-image-classifier-worker-prod   | 2025-07-15 10:54:05.259752: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
pl-ai-image-classifier-worker-prod   | 2025-07-15 10:54:05.288790: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:05.311537+00:00 [info] <0.763.0> accepting AMQP connection <0.763.0> (172.25.0.22:60276 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:05.315256+00:00 [info] <0.763.0> connection <0.763.0> (172.25.0.22:60276 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:05.345872+00:00 [warning] <0.763.0> closing AMQP connection <0.763.0> (172.25.0.22:60276 -> 172.25.0.5:5672, vhost: '/', user: 'admin'):
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:05.345872+00:00 [warning] <0.763.0> client unexpectedly closed TCP connection
pl-ai-rag-service-prod               | RabbitMQ pronto!
pl-ai-rag-service-prod               | Eseguendo le migrazioni...
pl-ai-resource-manager-worker-prod   | /usr/local/lib/python3.10/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
pl-ai-resource-manager-worker-prod   | absolutely not recommended!
pl-ai-resource-manager-worker-prod   | 
pl-ai-resource-manager-worker-prod   | Please specify a different user using the --uid option.
pl-ai-resource-manager-worker-prod   | 
pl-ai-resource-manager-worker-prod   | User information: uid=0 euid=0 gid=0 egid=0
pl-ai-resource-manager-worker-prod   | 
pl-ai-resource-manager-worker-prod   |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
pl-ai-resource-manager-worker-prod   |  
pl-ai-resource-manager-worker-prod   |  -------------- celery@08cf516029b7 v5.3.6 (emerald-rush)
pl-ai-resource-manager-worker-prod   | --- ***** ----- 
pl-ai-resource-manager-worker-prod   | -- ******* ---- Linux-6.1.0-37-amd64-x86_64-with-glibc2.36 2025-07-15 10:54:05
pl-ai-resource-manager-worker-prod   | - *** --- * --- 
pl-ai-resource-manager-worker-prod   | - ** ---------- [config]
pl-ai-resource-manager-worker-prod   | - ** ---------- .> app:         service_config:0x7f10d38d00d0
pl-ai-resource-manager-worker-prod   | - ** ---------- .> transport:   amqp://admin:**@rabbitmq:5672//
pl-ai-resource-manager-worker-prod   | - ** ---------- .> results:     disabled://
pl-ai-resource-manager-worker-prod   | - *** --- * --- .> concurrency: 2 (prefork)
pl-ai-resource-manager-worker-prod   | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
pl-ai-resource-manager-worker-prod   | --- ***** ----- 
pl-ai-resource-manager-worker-prod   |  -------------- [queues]
pl-ai-resource-manager-worker-prod   |                 .> resource_tasks   exchange=resource_tasks(direct) key=resource_tasks
pl-ai-resource-manager-worker-prod   |                 
pl-ai-resource-manager-worker-prod   | 
pl-ai-resource-manager-worker-prod   | [tasks]
pl-ai-resource-manager-worker-prod   |   . resources_api.tasks.process_uploaded_resource
pl-ai-resource-manager-worker-prod   |   . service_config.celery.debug_task
pl-ai-resource-manager-worker-prod   | 
pl-ai-classifier-service-prod        | 2025-07-15 10:54:05.941896: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
pl-ai-classifier-service-prod        | 2025-07-15 10:54:05.941932: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
pl-ai-classifier-service-prod        | 2025-07-15 10:54:05.961882: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
pl-ai-resource-manager-service-prod  | Using separate DB variables: dbname=resource_db user=resource_user host=resource_db
pl-ai-resource-manager-worker-prod   | [2025-07-15 10:54:07,399: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
pl-ai-resource-manager-worker-prod   | whether broker connection retries are made during startup in Celery 6.0 and above.
pl-ai-resource-manager-worker-prod   | If you wish to retain the existing behavior for retrying connections on startup,
pl-ai-resource-manager-worker-prod   | you should set broker_connection_retry_on_startup to True.
pl-ai-resource-manager-worker-prod   |   warnings.warn(
pl-ai-resource-manager-worker-prod   | 
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:07.503240+00:00 [info] <0.773.0> accepting AMQP connection <0.773.0> (172.25.0.16:56266 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:07.528570+00:00 [info] <0.773.0> connection <0.773.0> (172.25.0.16:56266 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-resource-manager-worker-prod   | [2025-07-15 10:54:07,529: INFO/MainProcess] Connected to amqp://admin:**@rabbitmq:5672//
pl-ai-resource-manager-worker-prod   | [2025-07-15 10:54:07,546: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
pl-ai-resource-manager-worker-prod   | whether broker connection retries are made during startup in Celery 6.0 and above.
pl-ai-resource-manager-worker-prod   | If you wish to retain the existing behavior for retrying connections on startup,
pl-ai-resource-manager-worker-prod   | you should set broker_connection_retry_on_startup to True.
pl-ai-resource-manager-worker-prod   |   warnings.warn(
pl-ai-resource-manager-worker-prod   | 
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:07.592140+00:00 [info] <0.781.0> accepting AMQP connection <0.781.0> (172.25.0.16:56276 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:07.597584+00:00 [info] <0.781.0> connection <0.781.0> (172.25.0.16:56276 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-resource-manager-worker-prod   | [2025-07-15 10:54:07,598: INFO/MainProcess] mingle: searching for neighbors
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:07.731167+00:00 [info] <0.799.0> accepting AMQP connection <0.799.0> (172.25.0.16:56292 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:07.752600+00:00 [info] <0.799.0> connection <0.799.0> (172.25.0.16:56292 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-resource-manager-worker-prod   | [2025-07-15 10:54:08,808: INFO/MainProcess] mingle: all alone
pl-ai-resource-manager-worker-prod   | [2025-07-15 10:54:08,875: INFO/MainProcess] celery@08cf516029b7 ready.
pl-ai-learning-service-prod          | OpenAI client inizializzato con successo
pl-ai-learning-service-prod          | Operations to perform:
pl-ai-learning-service-prod          |   Apply all migrations: admin, auth, contenttypes, learning_api, sessions
pl-ai-learning-service-prod          | Running migrations:
pl-ai-learning-service-prod          |   No migrations to apply.
pl-ai-learning-service-prod          | Creating superuser...
pl-ai-rag-service-prod               | Docker Secret file non trovato: /run/secrets/OPENAI_API_KEY
pl-ai-learning-service-prod          | Superuser already exists
pl-ai-resource-manager-service-prod  | Using separate DB variables: dbname=resource_db user=resource_user host=resource_db
pl-ai-resource-manager-service-prod  | Performing system checks...
pl-ai-resource-manager-service-prod  | 
pl-ai-resource-manager-service-prod  | Watching for file changes with StatReloader
pl-ai-learning-service-prod          | 
pl-ai-learning-service-prod          | 160 static files copied to '/app/staticfiles'.
pl-ai-learning-service-prod          | Starting learning service...
pl-ai-data-analysis-worker-prod      | OpenAI client initialized in tasks.py.
pl-ai-data-analysis-service-prod     | OpenAI client initialized in tasks.py.
pl-ai-data-analysis-worker-prod      | OpenAI client initialized in views.
pl-ai-data-analysis-service-prod     | OpenAI client initialized in views.
pl-ai-data-analysis-worker-prod      | /usr/local/lib/python3.10/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
pl-ai-data-analysis-worker-prod      | absolutely not recommended!
pl-ai-data-analysis-worker-prod      | 
pl-ai-data-analysis-worker-prod      | Please specify a different user using the --uid option.
pl-ai-data-analysis-worker-prod      | 
pl-ai-data-analysis-worker-prod      | User information: uid=0 euid=0 gid=0 egid=0
pl-ai-data-analysis-worker-prod      | 
pl-ai-data-analysis-worker-prod      |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
pl-ai-data-analysis-service-prod     | Operations to perform:
pl-ai-data-analysis-service-prod     |   Apply all migrations: admin, analysis_api, auth, contenttypes, sessions
pl-ai-data-analysis-service-prod     | Running migrations:
pl-ai-data-analysis-service-prod     |   No migrations to apply.
pl-ai-data-analysis-worker-prod      |  
pl-ai-data-analysis-worker-prod      |  -------------- celery@1655feb2e86d v5.3.6 (emerald-rush)
pl-ai-data-analysis-worker-prod      | --- ***** ----- 
pl-ai-data-analysis-worker-prod      | -- ******* ---- Linux-6.1.0-37-amd64-x86_64-with-glibc2.36 2025-07-15 10:54:19
pl-ai-data-analysis-worker-prod      | - *** --- * --- 
pl-ai-data-analysis-worker-prod      | - ** ---------- [config]
pl-ai-data-analysis-worker-prod      | - ** ---------- .> app:         service_config:0x7fbfb67b4970
pl-ai-data-analysis-worker-prod      | - ** ---------- .> transport:   amqp://admin:**@rabbitmq:5672//
pl-ai-data-analysis-worker-prod      | - ** ---------- .> results:     disabled://
pl-ai-data-analysis-worker-prod      | - *** --- * --- .> concurrency: 1 (prefork)
pl-ai-data-analysis-worker-prod      | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
pl-ai-data-analysis-worker-prod      | --- ***** ----- 
pl-ai-data-analysis-worker-prod      |  -------------- [queues]
pl-ai-data-analysis-worker-prod      |                 .> analysis_tasks   exchange=analysis_tasks(direct) key=analysis_tasks
pl-ai-data-analysis-worker-prod      |                 
pl-ai-data-analysis-worker-prod      | 
pl-ai-data-analysis-worker-prod      | [tasks]
pl-ai-data-analysis-worker-prod      |   . analysis_api.tasks.generate_synthetic_csv_task
pl-ai-data-analysis-worker-prod      |   . analysis_api.tasks.run_analysis_task
pl-ai-data-analysis-worker-prod      | 
pl-ai-data-analysis-worker-prod      | [2025-07-15 10:54:21,016: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
pl-ai-data-analysis-worker-prod      | whether broker connection retries are made during startup in Celery 6.0 and above.
pl-ai-data-analysis-worker-prod      | If you wish to retain the existing behavior for retrying connections on startup,
pl-ai-data-analysis-worker-prod      | you should set broker_connection_retry_on_startup to True.
pl-ai-data-analysis-worker-prod      |   warnings.warn(
pl-ai-data-analysis-worker-prod      | 
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:21.157145+00:00 [info] <0.849.0> accepting AMQP connection <0.849.0> (172.25.0.25:52358 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:21.188916+00:00 [info] <0.849.0> connection <0.849.0> (172.25.0.25:52358 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-data-analysis-worker-prod      | [2025-07-15 10:54:21,197: INFO/MainProcess] Connected to amqp://admin:**@rabbitmq:5672//
pl-ai-data-analysis-worker-prod      | [2025-07-15 10:54:21,203: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
pl-ai-data-analysis-worker-prod      | whether broker connection retries are made during startup in Celery 6.0 and above.
pl-ai-data-analysis-worker-prod      | If you wish to retain the existing behavior for retrying connections on startup,
pl-ai-data-analysis-worker-prod      | you should set broker_connection_retry_on_startup to True.
pl-ai-data-analysis-worker-prod      |   warnings.warn(
pl-ai-data-analysis-worker-prod      | 
pl-ai-image-generator-service-prod   | [15/Jul/2025 10:54:21] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:21.291540+00:00 [info] <0.857.0> accepting AMQP connection <0.857.0> (172.25.0.25:52360 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:21.307880+00:00 [info] <0.857.0> connection <0.857.0> (172.25.0.25:52360 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-data-analysis-worker-prod      | [2025-07-15 10:54:21,311: INFO/MainProcess] mingle: searching for neighbors
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:21.450424+00:00 [info] <0.874.0> accepting AMQP connection <0.874.0> (172.25.0.25:52368 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:21.472350+00:00 [info] <0.874.0> connection <0.874.0> (172.25.0.25:52368 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-resource-manager-worker-prod   | [2025-07-15 10:54:21,476: INFO/MainProcess] sync with celery@1655feb2e86d
pl-ai-auth-service-prod              | [15/Jul/2025 10:54:21] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-chatbot-service-prod           | [15/Jul/2025 10:54:21] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-classifier-service-prod        | Operations to perform:
pl-ai-classifier-service-prod        |   Apply all migrations: admin, auth, classifier_api, contenttypes, sessions
pl-ai-classifier-service-prod        | Running migrations:
pl-ai-classifier-service-prod        |   No migrations to apply.
pl-ai-user-service-prod              | Watching for file changes with StatReloader
pl-ai-user-service-prod              | Performing system checks...
pl-ai-user-service-prod              | 
pl-ai-data-analysis-worker-prod      | [2025-07-15 10:54:22,508: INFO/MainProcess] mingle: sync with 1 nodes
pl-ai-data-analysis-worker-prod      | [2025-07-15 10:54:22,508: INFO/MainProcess] mingle: sync complete
pl-ai-data-analysis-worker-prod      | [2025-07-15 10:54:22,560: INFO/MainProcess] celery@1655feb2e86d ready.
pl-ai-image-classifier-worker-prod   | /usr/local/lib/python3.10/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
pl-ai-image-classifier-worker-prod   | absolutely not recommended!
pl-ai-image-classifier-worker-prod   | 
pl-ai-image-classifier-worker-prod   | Please specify a different user using the --uid option.
pl-ai-image-classifier-worker-prod   | 
pl-ai-image-classifier-worker-prod   | User information: uid=0 euid=0 gid=0 egid=0
pl-ai-image-classifier-worker-prod   | 
pl-ai-image-classifier-worker-prod   |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
pl-ai-image-classifier-worker-prod   |  
pl-ai-image-classifier-worker-prod   |  -------------- celery@6ae73a6640bd v5.3.6 (emerald-rush)
pl-ai-image-classifier-worker-prod   | --- ***** ----- 
pl-ai-image-classifier-worker-prod   | -- ******* ---- Linux-6.1.0-37-amd64-x86_64-with-glibc2.36 2025-07-15 10:54:23
pl-ai-image-classifier-worker-prod   | - *** --- * --- 
pl-ai-image-classifier-worker-prod   | - ** ---------- [config]
pl-ai-image-classifier-worker-prod   | - ** ---------- .> app:         service_config:0x7efee5e30970
pl-ai-image-classifier-worker-prod   | - ** ---------- .> transport:   amqp://admin:**@rabbitmq:5672//
pl-ai-image-classifier-worker-prod   | - ** ---------- .> results:     disabled://
pl-ai-image-classifier-worker-prod   | - *** --- * --- .> concurrency: 1 (prefork)
pl-ai-image-classifier-worker-prod   | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
pl-ai-image-classifier-worker-prod   | --- ***** ----- 
pl-ai-image-classifier-worker-prod   |  -------------- [queues]
pl-ai-image-classifier-worker-prod   |                 .> classifier_tasks exchange=classifier_tasks(direct) key=classifier_tasks
pl-ai-image-classifier-worker-prod   |                 
pl-ai-image-classifier-worker-prod   | 
pl-ai-image-classifier-worker-prod   | [tasks]
pl-ai-image-classifier-worker-prod   |   . classifier_api.tasks.train_classifier_task
pl-ai-image-classifier-worker-prod   |   . service_config.celery.debug_task
pl-ai-image-classifier-worker-prod   | 
pl-ai-resource-manager-service-prod  | System check identified no issues (0 silenced).
pl-ai-learning-service-prod          | Watching for file changes with StatReloader
pl-ai-data-analysis-service-prod     | Starting process type: web
pl-ai-data-analysis-service-prod     | Starting Django development server on port 8000...
pl-ai-resource-manager-service-prod  | July 15, 2025 - 10:54:23
pl-ai-resource-manager-service-prod  | Django version 4.2.23, using settings 'service_config.settings'
pl-ai-resource-manager-service-prod  | Starting development server at http://0.0.0.0:8000/
pl-ai-resource-manager-service-prod  | Quit the server with CONTROL-C.
pl-ai-resource-manager-service-prod  | 
pl-ai-image-classifier-worker-prod   | [2025-07-15 10:54:24,224: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
pl-ai-image-classifier-worker-prod   | whether broker connection retries are made during startup in Celery 6.0 and above.
pl-ai-image-classifier-worker-prod   | If you wish to retain the existing behavior for retrying connections on startup,
pl-ai-image-classifier-worker-prod   | you should set broker_connection_retry_on_startup to True.
pl-ai-image-classifier-worker-prod   |   warnings.warn(
pl-ai-image-classifier-worker-prod   | 
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:24.289396+00:00 [info] <0.922.0> accepting AMQP connection <0.922.0> (172.25.0.19:53832 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:24.304915+00:00 [info] <0.922.0> connection <0.922.0> (172.25.0.19:53832 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-image-classifier-worker-prod   | [2025-07-15 10:54:24,312: INFO/MainProcess] Connected to amqp://admin:**@rabbitmq:5672//
pl-ai-image-classifier-worker-prod   | [2025-07-15 10:54:24,314: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
pl-ai-image-classifier-worker-prod   | whether broker connection retries are made during startup in Celery 6.0 and above.
pl-ai-image-classifier-worker-prod   | If you wish to retain the existing behavior for retrying connections on startup,
pl-ai-image-classifier-worker-prod   | you should set broker_connection_retry_on_startup to True.
pl-ai-image-classifier-worker-prod   |   warnings.warn(
pl-ai-image-classifier-worker-prod   | 
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:24.343437+00:00 [info] <0.930.0> accepting AMQP connection <0.930.0> (172.25.0.19:53840 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:24.356349+00:00 [info] <0.930.0> connection <0.930.0> (172.25.0.19:53840 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-image-classifier-worker-prod   | [2025-07-15 10:54:24,395: INFO/MainProcess] mingle: searching for neighbors
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:24.480051+00:00 [info] <0.952.0> accepting AMQP connection <0.952.0> (172.25.0.19:53842 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:54:24.487611+00:00 [info] <0.952.0> connection <0.952.0> (172.25.0.19:53842 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-data-analysis-worker-prod      | [2025-07-15 10:54:24,505: INFO/MainProcess] sync with celery@6ae73a6640bd
pl-ai-resource-manager-worker-prod   | [2025-07-15 10:54:24,505: INFO/MainProcess] sync with celery@6ae73a6640bd
pl-ai-user-service-prod              | System check identified no issues (0 silenced).
pl-ai-user-service-prod              | July 15, 2025 - 10:54:25
pl-ai-user-service-prod              | Django version 4.2.23, using settings 'service_config.settings'
pl-ai-user-service-prod              | Starting development server at http://0.0.0.0:8000/
pl-ai-user-service-prod              | Quit the server with CONTROL-C.
pl-ai-user-service-prod              | 
pl-ai-image-classifier-worker-prod   | [2025-07-15 10:54:25,533: INFO/MainProcess] mingle: sync with 2 nodes
pl-ai-image-classifier-worker-prod   | [2025-07-15 10:54:25,534: INFO/MainProcess] mingle: sync complete
pl-ai-image-classifier-worker-prod   | [2025-07-15 10:54:25,581: INFO/MainProcess] celery@6ae73a6640bd ready.
pl-ai-classifier-service-prod        | Starting process type: web
pl-ai-classifier-service-prod        | Starting Django development server on port 8000...
pl-ai-rag-worker-prod                | Caricando modello: all-MiniLM-L6-v2
pl-ai-learning-service-prod          | OpenAI client inizializzato con successo
modules.json: 100%|██████████| 349/349 [00:00<00:00, 275kB/s]
config_sentence_transformers.json: 100%|██████████| 116/116 [00:00<00:00, 572kB/s]
README.md: 10.5kB [00:00, 9.21MB/s]  | 
sentence_bert_config.json: 100%|██████████| 53.0/53.0 [00:00<00:00, 149kB/s]
config.json: 100%|██████████| 612/612 [00:00<00:00, 2.22MB/s]
pl-ai-data-analysis-service-prod     | Watching for file changes with StatReloader
pl-ai-data-analysis-service-prod     | Performing system checks...
pl-ai-data-analysis-service-prod     | 
pl-ai-classifier-service-prod        | Watching for file changes with StatReloader
pl-ai-classifier-service-prod        | Performing system checks...
pl-ai-classifier-service-prod        | 
pl-ai-rag-service-prod               | INFO 2025-07-15 12:54:34,742 loader 10 140007270161280 Loading faiss with AVX2 support.
pl-ai-rag-service-prod               | INFO 2025-07-15 12:54:35,074 loader 10 140007270161280 Successfully loaded faiss with AVX2 support.
pl-ai-classifier-service-prod        | 2025-07-15 10:54:36.346753: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
pl-ai-classifier-service-prod        | 2025-07-15 10:54:36.347454: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
pl-ai-rag-service-prod               | No changes detected
pl-ai-classifier-service-prod        | 2025-07-15 10:54:36.543977: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
pl-ai-data-analysis-service-prod     | OpenAI client initialized in tasks.py.
pl-ai-data-analysis-service-prod     | OpenAI client initialized in views.
pl-ai-data-analysis-service-prod     | System check identified no issues (0 silenced).
pl-ai-data-analysis-service-prod     | July 15, 2025 - 10:54:38
pl-ai-data-analysis-service-prod     | Django version 4.2.23, using settings 'service_config.settings'
pl-ai-data-analysis-service-prod     | Starting development server at http://0.0.0.0:8000/
pl-ai-data-analysis-service-prod     | Quit the server with CONTROL-C.
pl-ai-data-analysis-service-prod     | 
pl-ai-rag-service-prod               | Docker Secret file non trovato: /run/secrets/OPENAI_API_KEY
pl-ai-classifier-service-prod        | System check identified no issues (0 silenced).
pl-ai-classifier-service-prod        | July 15, 2025 - 10:54:42
pl-ai-classifier-service-prod        | Django version 4.2.23, using settings 'service_config.settings'
pl-ai-classifier-service-prod        | Starting development server at http://0.0.0.0:8000/
pl-ai-classifier-service-prod        | Quit the server with CONTROL-C.
pl-ai-classifier-service-prod        | 
model.safetensors: 100%|██████████| 90.9M/90.9M [00:11<00:00, 8.05MB/s]
tokenizer_config.json: 100%|██████████| 350/350 [00:00<00:00, 1.52MB/s]
vocab.txt: 232kB [00:00, 8.62MB/s]   | 
tokenizer.json: 466kB [00:00, 26.9MB/s]
special_tokens_map.json: 100%|██████████| 112/112 [00:00<00:00, 399kB/s]
config.json: 100%|██████████| 190/190 [00:00<00:00, 367kB/s]
pl-ai-rag-worker-prod                | Modello caricato con successo!
pl-ai-resource-manager-service-prod  | [15/Jul/2025 10:54:49] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-classifier-service-prod        | [15/Jul/2025 10:54:51] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-rag-worker-prod                | Docker Secret file non trovato: /run/secrets/OPENAI_API_KEY
pl-ai-learning-service-prod          | "GET /admin/login/ HTTP/1.1" 200 4193
pl-ai-rag-service-prod               | INFO 2025-07-15 12:54:53,261 loader 15 140275315460992 Loading faiss with AVX2 support.
pl-ai-rag-service-prod               | INFO 2025-07-15 12:54:53,596 loader 15 140275315460992 Successfully loaded faiss with AVX2 support.
pl-ai-user-service-prod              | [15/Jul/2025 10:54:53] "GET /admin/login/ HTTP/1.1" 200 4178
pl-ai-data-analysis-service-prod     | [15/Jul/2025 10:54:54] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-rag-service-prod               | Operations to perform:
pl-ai-rag-service-prod               |   Apply all migrations: admin, auth, contenttypes, rag_api, sessions
pl-ai-rag-service-prod               | Running migrations:
pl-ai-rag-service-prod               |   Applying contenttypes.0001_initial... OK
pl-ai-rag-service-prod               |   Applying auth.0001_initial... OK
pl-ai-rag-service-prod               |   Applying admin.0001_initial... OK
pl-ai-rag-service-prod               |   Applying admin.0002_logentry_remove_auto_add... OK
pl-ai-rag-service-prod               |   Applying admin.0003_logentry_add_action_flag_choices... OK
pl-ai-rag-service-prod               |   Applying contenttypes.0002_remove_content_type_name... OK
pl-ai-rag-service-prod               |   Applying auth.0002_alter_permission_name_max_length... OK
pl-ai-rag-service-prod               |   Applying auth.0003_alter_user_email_max_length... OK
pl-ai-rag-service-prod               |   Applying auth.0004_alter_user_username_opts... OK
pl-ai-rag-service-prod               |   Applying auth.0005_alter_user_last_login_null... OK
pl-ai-rag-service-prod               |   Applying auth.0006_require_contenttypes_0002... OK
pl-ai-rag-service-prod               |   Applying auth.0007_alter_validators_add_error_messages... OK
pl-ai-rag-service-prod               |   Applying auth.0008_alter_user_username_max_length... OK
pl-ai-rag-service-prod               |   Applying auth.0009_alter_user_last_name_max_length... OK
pl-ai-rag-service-prod               |   Applying auth.0010_alter_group_name_max_length... OK
pl-ai-rag-service-prod               |   Applying auth.0011_update_proxy_permissions... OK
pl-ai-rag-service-prod               |   Applying auth.0012_alter_user_first_name_max_length... OK
pl-ai-rag-service-prod               |   Applying rag_api.0001_initial... OK
pl-ai-rag-service-prod               |   Applying rag_api.0002_ragchatsession_ragchatmessage_and_more... OK
pl-ai-rag-service-prod               |   Applying rag_api.0002_add_resource_id... OK
pl-ai-rag-service-prod               |   Applying rag_api.0003_merge_20250624_1134... OK
pl-ai-rag-service-prod               |   Applying sessions.0001_initial... OK
pl-ai-rag-service-prod               | Verificando modello Sentence Transformers...
pl-ai-rag-worker-prod                | INFO 2025-07-15 12:54:59,996 loader 1 139825727511424 Loading faiss with AVX2 support.
pl-ai-rag-worker-prod                | INFO 2025-07-15 12:55:00,023 loader 1 139825727511424 Successfully loaded faiss with AVX2 support.
pl-ai-rag-worker-prod                | /usr/local/lib/python3.11/site-packages/celery/platforms.py:829: SecurityWarning: You're running the worker with superuser privileges: this is
pl-ai-rag-worker-prod                | absolutely not recommended!
pl-ai-rag-worker-prod                | 
pl-ai-rag-worker-prod                | Please specify a different user using the --uid option.
pl-ai-rag-worker-prod                | 
pl-ai-rag-worker-prod                | User information: uid=0 euid=0 gid=0 egid=0
pl-ai-rag-worker-prod                | 
pl-ai-rag-worker-prod                |   warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
pl-ai-rag-worker-prod                |  
pl-ai-rag-worker-prod                |  -------------- celery@7f026e29fc14 v5.3.4 (emerald-rush)
pl-ai-rag-worker-prod                | --- ***** ----- 
pl-ai-rag-worker-prod                | -- ******* ---- Linux-6.1.0-37-amd64-x86_64-with-glibc2.36 2025-07-15 12:55:00
pl-ai-rag-worker-prod                | - *** --- * --- 
pl-ai-rag-worker-prod                | - ** ---------- [config]
pl-ai-rag-worker-prod                | - ** ---------- .> app:         rag_service:0x7f2bb51dded0
pl-ai-rag-worker-prod                | - ** ---------- .> transport:   amqp://admin:**@rabbitmq:5672//
pl-ai-rag-worker-prod                | - ** ---------- .> results:     rpc://
pl-ai-rag-worker-prod                | - *** --- * --- .> concurrency: 1 (prefork)
pl-ai-rag-worker-prod                | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
pl-ai-rag-worker-prod                | --- ***** ----- 
pl-ai-rag-worker-prod                |  -------------- [queues]
pl-ai-rag-worker-prod                |                 .> rag_tasks        exchange=rag_tasks(direct) key=rag_tasks
pl-ai-rag-worker-prod                |                 
pl-ai-rag-worker-prod                | 
pl-ai-rag-worker-prod                | [tasks]
pl-ai-rag-worker-prod                |   . rag_api.tasks.cleanup_failed_documents
pl-ai-rag-worker-prod                |   . rag_api.tasks.process_document
pl-ai-rag-worker-prod                |   . rag_api.tasks.process_query
pl-ai-rag-worker-prod                |   . rag_api.tasks.process_rag_document_task
pl-ai-rag-worker-prod                |   . rag_api.tasks.reprocess_document_task
pl-ai-rag-worker-prod                | 
pl-ai-rag-worker-prod                | [2025-07-15 12:55:00,918: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
pl-ai-rag-worker-prod                | whether broker connection retries are made during startup in Celery 6.0 and above.
pl-ai-rag-worker-prod                | If you wish to retain the existing behavior for retrying connections on startup,
pl-ai-rag-worker-prod                | you should set broker_connection_retry_on_startup to True.
pl-ai-rag-worker-prod                |   warnings.warn(
pl-ai-rag-worker-prod                | 
pl-ai-rabbitmq-prod                  | 2025-07-15 10:55:00.923905+00:00 [info] <0.1026.0> accepting AMQP connection <0.1026.0> (172.25.0.21:48496 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:55:00.928390+00:00 [info] <0.1026.0> connection <0.1026.0> (172.25.0.21:48496 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-rag-worker-prod                | [2025-07-15 12:55:00,929: INFO/MainProcess] Connected to amqp://admin:**@rabbitmq:5672//
pl-ai-rag-worker-prod                | [2025-07-15 12:55:00,936: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:507: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
pl-ai-rag-worker-prod                | whether broker connection retries are made during startup in Celery 6.0 and above.
pl-ai-rag-worker-prod                | If you wish to retain the existing behavior for retrying connections on startup,
pl-ai-rag-worker-prod                | you should set broker_connection_retry_on_startup to True.
pl-ai-rag-worker-prod                |   warnings.warn(
pl-ai-rag-worker-prod                | 
pl-ai-rabbitmq-prod                  | 2025-07-15 10:55:00.939341+00:00 [info] <0.1034.0> accepting AMQP connection <0.1034.0> (172.25.0.21:48512 -> 172.25.0.5:5672)
pl-ai-rabbitmq-prod                  | 2025-07-15 10:55:00.941954+00:00 [info] <0.1034.0> connection <0.1034.0> (172.25.0.21:48512 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-rag-worker-prod                | [2025-07-15 12:55:00,945: INFO/MainProcess] mingle: searching for neighbors
pl-ai-image-classifier-worker-prod   | [2025-07-15 10:55:00,946: WARNING/MainProcess] Substantial drift from celery@7f026e29fc14 may mean clocks are out of sync.  Current drift is 7200 seconds.  [orig: 2025-07-15 10:55:00.946741 recv: 2025-07-15 12:55:00.943041]
pl-ai-data-analysis-worker-prod      | [2025-07-15 10:55:00,948: WARNING/MainProcess] Substantial drift from celery@7f026e29fc14 may mean clocks are out of sync.  Current drift is 7200 seconds.  [orig: 2025-07-15 10:55:00.946758 recv: 2025-07-15 12:55:00.943041]
pl-ai-resource-manager-worker-prod   | [2025-07-15 10:55:00,951: WARNING/MainProcess] Substantial drift from celery@7f026e29fc14 may mean clocks are out of sync.  Current drift is 7200 seconds.  [orig: 2025-07-15 10:55:00.947412 recv: 2025-07-15 12:55:00.943041]
pl-ai-rabbitmq-prod                  | 2025-07-15 10:55:00.960401+00:00 [info] <0.1056.0> accepting AMQP connection <0.1056.0> (172.25.0.21:48516 -> 172.25.0.5:5672)
pl-ai-data-analysis-worker-prod      | [2025-07-15 10:55:00,965: INFO/MainProcess] sync with celery@7f026e29fc14
pl-ai-resource-manager-worker-prod   | [2025-07-15 10:55:00,968: INFO/MainProcess] sync with celery@7f026e29fc14
pl-ai-image-classifier-worker-prod   | [2025-07-15 10:55:00,967: INFO/MainProcess] sync with celery@7f026e29fc14
pl-ai-rabbitmq-prod                  | 2025-07-15 10:55:00.962851+00:00 [info] <0.1056.0> connection <0.1056.0> (172.25.0.21:48516 -> 172.25.0.5:5672): user 'admin' authenticated and granted access to vhost '/'
pl-ai-rag-worker-prod                | [2025-07-15 12:55:01,980: INFO/MainProcess] mingle: sync with 3 nodes
pl-ai-rag-worker-prod                | [2025-07-15 12:55:01,981: INFO/MainProcess] mingle: sync complete
pl-ai-rag-worker-prod                | [2025-07-15 12:55:02,009: INFO/MainProcess] celery@7f026e29fc14 ready.
pl-ai-rag-worker-prod                | [2025-07-15 12:55:02,450: WARNING/MainProcess] Substantial drift from celery@6ae73a6640bd may mean clocks are out of sync.  Current drift is 7200 seconds.  [orig: 2025-07-15 12:55:02.450005 recv: 2025-07-15 10:55:02.447080]
pl-ai-rag-worker-prod                | [2025-07-15 12:55:02,590: WARNING/MainProcess] Substantial drift from celery@1655feb2e86d may mean clocks are out of sync.  Current drift is 7200 seconds.  [orig: 2025-07-15 12:55:02.590137 recv: 2025-07-15 10:55:02.587291]
pl-ai-rag-worker-prod                | [2025-07-15 12:55:02,919: WARNING/MainProcess] Substantial drift from celery@08cf516029b7 may mean clocks are out of sync.  Current drift is 7200 seconds.  [orig: 2025-07-15 12:55:02.919721 recv: 2025-07-15 10:55:02.917738]
pl-ai-rag-service-prod               | Caricando modello: all-MiniLM-L6-v2
modules.json: 100%|██████████| 349/349 [00:00<00:00, 1.33MB/s]
config_sentence_transformers.json: 100%|██████████| 116/116 [00:00<00:00, 496kB/s]
README.md: 10.5kB [00:00, 21.8MB/s]  | 
sentence_bert_config.json: 100%|██████████| 53.0/53.0 [00:00<00:00, 257kB/s]
config.json: 100%|██████████| 612/612 [00:00<00:00, 2.19MB/s]
model.safetensors: 100%|██████████| 90.9M/90.9M [00:04<00:00, 19.1MB/s]
tokenizer_config.json: 100%|██████████| 350/350 [00:00<00:00, 1.48MB/s]
vocab.txt: 232kB [00:00, 6.72MB/s]   | 
tokenizer.json: 466kB [00:00, 1.06MB/s]
special_tokens_map.json: 100%|██████████| 112/112 [00:00<00:00, 499kB/s]
config.json: 100%|██████████| 190/190 [00:00<00:00, 587kB/s]
pl-ai-rag-service-prod               | Modello caricato con successo!
pl-ai-rag-service-prod               | [2025-07-15 10:55:14 +0000] [1] [INFO] Starting gunicorn 21.2.0
pl-ai-rag-service-prod               | [2025-07-15 10:55:14 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
pl-ai-rag-service-prod               | [2025-07-15 10:55:14 +0000] [1] [INFO] Using worker: sync
pl-ai-rag-service-prod               | [2025-07-15 10:55:14 +0000] [34] [INFO] Booting worker with pid: 34
pl-ai-rag-service-prod               | Docker Secret file non trovato: /run/secrets/OPENAI_API_KEY
pl-ai-image-generator-service-prod   | [15/Jul/2025 10:55:21] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-chatbot-service-prod           | [15/Jul/2025 10:55:21] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-auth-service-prod              | [15/Jul/2025 10:55:21] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-resource-manager-service-prod  | [15/Jul/2025 10:55:49] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-classifier-service-prod        | [15/Jul/2025 10:55:51] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-learning-service-prod          | "GET /admin/login/ HTTP/1.1" 200 4193
pl-ai-user-service-prod              | [15/Jul/2025 10:55:54] "GET /admin/login/ HTTP/1.1" 200 4178
pl-ai-data-analysis-service-prod     | [15/Jul/2025 10:55:54] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-rag-service-prod               | INFO 2025-07-15 12:56:00,057 loader 34 140015128198016 Loading faiss with AVX2 support.
pl-ai-rag-service-prod               | INFO 2025-07-15 12:56:00,082 loader 34 140015128198016 Successfully loaded faiss with AVX2 support.
pl-ai-nginx-prod                     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
pl-ai-nginx-prod                     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
pl-ai-nginx-prod                     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
pl-ai-nginx-prod                     | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
pl-ai-nginx-prod                     | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
pl-ai-nginx-prod                     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
pl-ai-nginx-prod                     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
pl-ai-nginx-prod                     | /docker-entrypoint.sh: Configuration complete; ready for start up
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:11 AM 172.25.0.26 GET /
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:11 AM 172.25.0.26 Returned 200 in 197 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:11 +0000] "GET / HTTP/1.0" 200 460 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:11 AM 172.25.0.26 GET /assets/index-LksxMZE5.js
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:11 AM 172.25.0.26 Returned 200 in 47 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:11 AM 172.25.0.26 GET /assets/index-Ba6aqRrq.css
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:11 AM 172.25.0.26 Returned 200 in 73 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:12 +0000] "GET /assets/index-Ba6aqRrq.css HTTP/1.0" 200 225246 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:12 +0000] "GET /assets/index-LksxMZE5.js HTTP/1.0" 200 2064929 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:12 AM 172.25.0.26 GET /assets/uicons-regular-rounded-J3WOUERV-0sU45oCT.woff2
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:12 AM 172.25.0.26 Returned 200 in 6 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:12 +0000] "GET /assets/uicons-regular-rounded-J3WOUERV-0sU45oCT.woff2 HTTP/1.0" 200 385636 "https://dev.pl-ai.it/assets/index-Ba6aqRrq.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | Unauthorized: /api/v1/social-auth/config/
pl-ai-auth-service-prod              | [15/Jul/2025 10:56:12] "GET /api/v1/social-auth/config/ HTTP/1.0" 401 183
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:12 +0000] "GET /api/v1/social-auth/config/ HTTP/1.0" 401 183 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:18 AM 172.25.0.26 GET /assets/index-Ba6aqRrq.css
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:18 +0000] "GET /assets/index-Ba6aqRrq.css HTTP/1.0" 304 0 "https://dev.pl-ai.it/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:18 AM 172.25.0.26 Returned 304 in 2 ms
pl-ai-image-generator-service-prod   | [15/Jul/2025 10:56:21] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-chatbot-service-prod           | [15/Jul/2025 10:56:22] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-auth-service-prod              | [15/Jul/2025 10:56:22] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:22 AM 172.25.0.26 GET /register
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:22 +0000] "GET /register HTTP/1.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:22 AM 172.25.0.26 Returned 304 in 1 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:22 AM 172.25.0.26 GET /assets/index-Ba6aqRrq.css
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:22 +0000] "GET /assets/index-Ba6aqRrq.css HTTP/1.0" 304 0 "https://dev.pl-ai.it/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:22 AM 172.25.0.26 Returned 304 in 2 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:22 AM 172.25.0.26 GET /assets/index-LksxMZE5.js
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:22 +0000] "GET /assets/index-LksxMZE5.js HTTP/1.0" 304 0 "https://dev.pl-ai.it/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:22 AM 172.25.0.26 Returned 304 in 2 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:23 AM 172.25.0.26 GET /assets/uicons-regular-rounded-J3WOUERV-0sU45oCT.woff2
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:23 AM 172.25.0.26 Returned 304 in 3 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:23 +0000] "GET /assets/uicons-regular-rounded-J3WOUERV-0sU45oCT.woff2 HTTP/1.0" 304 0 "https://dev.pl-ai.it/assets/index-Ba6aqRrq.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:56:23] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:23 +0000] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486 "https://dev.pl-ai.it/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:23 +0000] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62 "https://dev.pl-ai.it/register" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:56:23] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:29 AM 172.25.0.26 GET /
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:29 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:29 +0000] "GET / HTTP/1.0" 200 460 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:29 AM 172.25.0.26 GET /assets/index-LksxMZE5.js
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:29 +0000] "GET /assets/index-LksxMZE5.js HTTP/1.0" 304 0 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:29 AM 172.25.0.26 Returned 304 in 2 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:29 AM 172.25.0.26 GET /assets/index-Ba6aqRrq.css
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:29 +0000] "GET /assets/index-Ba6aqRrq.css HTTP/1.0" 304 0 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:29 AM 172.25.0.26 Returned 304 in 1 ms
pl-ai-auth-service-prod              | [15/Jul/2025 10:56:29] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:29 +0000] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:56:29] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:29 +0000] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-resource-manager-service-prod  | [15/Jul/2025 10:56:49] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-classifier-service-prod        | [15/Jul/2025 10:56:51] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-learning-service-prod          | "GET /admin/login/ HTTP/1.1" 200 4193
pl-ai-user-service-prod              | [15/Jul/2025 10:56:54] "GET /admin/login/ HTTP/1.1" 200 4178
pl-ai-data-analysis-service-prod     | [15/Jul/2025 10:56:54] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:57 AM 172.25.0.26 GET /auth/callback
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:57 AM 172.25.0.26 Returned 200 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:57 +0000] "GET /auth/callback HTTP/1.0" 200 460 "https://accounts.google.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:57 AM 172.25.0.26 GET /assets/index-LksxMZE5.js
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:57 AM 172.25.0.26 Returned 304 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:57 +0000] "GET /assets/index-LksxMZE5.js HTTP/1.0" 304 0 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:57 AM 172.25.0.26 GET /assets/index-Ba6aqRrq.css
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:57 +0000] "GET /assets/index-Ba6aqRrq.css HTTP/1.0" 304 0 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:57 AM 172.25.0.26 Returned 304 in 2 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:57 AM 172.25.0.26 GET /assets/uicons-regular-rounded-J3WOUERV-0sU45oCT.woff2
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:56:57 AM 172.25.0.26 Returned 304 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:57 +0000] "GET /assets/uicons-regular-rounded-J3WOUERV-0sU45oCT.woff2 HTTP/1.0" 304 0 "https://dev.pl-ai.it/assets/index-Ba6aqRrq.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:56:57] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:57 +0000] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:57 +0000] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:56:57] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:57 +0000] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:56:57] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62
pl-ai-auth-service-prod              | [15/Jul/2025 10:56:58] "POST /api/v1/social-auth/callback/ HTTP/1.0" 200 781
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:58 +0000] "POST /api/v1/social-auth/callback/ HTTP/1.0" 200 781 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:56:58] "GET /api/users/me/ HTTP/1.0" 400 16510
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:56:58 +0000] "GET /api/users/me/ HTTP/1.0" 400 16510 "https://dev.pl-ai.it/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:02 AM 172.25.0.26 GET /
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:02 AM 172.25.0.26 Returned 200 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:02 +0000] "GET / HTTP/1.0" 200 460 "-" "Sogou web spider/4.0(+http://www.sogou.com/docs/help/webmasters.htm#07)" "223.109.252.141"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:06 AM 172.25.0.26 GET /
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:06 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:06 +0000] "GET / HTTP/1.0" 200 460 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Google-PageRenderer Google (+https://developers.google.com/+/web/snippet/)" "66.249.80.4"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:19 AM 172.25.0.26 GET /
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:19 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:19 +0000] "GET / HTTP/1.0" 200 460 "https://www.google.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:19 AM 172.25.0.26 GET /assets/index-LksxMZE5.js
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:19 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:20 AM 172.25.0.26 GET /assets/index-Ba6aqRrq.css
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:20 +0000] "GET /assets/index-Ba6aqRrq.css HTTP/1.0" 304 0 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:20 AM 172.25.0.26 Returned 304 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:20 +0000] "GET /assets/index-LksxMZE5.js HTTP/1.0" 200 2064929 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:20 AM 172.25.0.26 GET /G-LAB_logo.png
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:20 AM 172.25.0.26 GET /golinelliAI.png
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:20 +0000] "GET /G-LAB_logo.png HTTP/1.0" 304 0 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:20 AM 172.25.0.26 Returned 304 in 10 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:20 +0000] "GET /golinelliAI.png HTTP/1.0" 304 0 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:20 AM 172.25.0.26 Returned 304 in 10 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:20 AM 172.25.0.26 GET /assets/uicons-regular-rounded-J3WOUERV-0sU45oCT.woff2
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:20 AM 172.25.0.26 Returned 200 in 1 ms
pl-ai-auth-service-prod              | Unauthorized: /api/v1/social-auth/config/
pl-ai-auth-service-prod              | [15/Jul/2025 10:57:20] "GET /api/v1/social-auth/config/ HTTP/1.0" 401 183
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:20 +0000] "GET /api/v1/social-auth/config/ HTTP/1.0" 401 183 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:20 +0000] "GET /assets/uicons-regular-rounded-J3WOUERV-0sU45oCT.woff2 HTTP/1.0" 200 385636 "https://dev.pl-ai.it/assets/index-Ba6aqRrq.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:20 AM 172.25.0.26 GET /LogoFG.png
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:20 +0000] "GET /LogoFG.png HTTP/1.0" 304 0 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:20 AM 172.25.0.26 Returned 304 in 3 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:20 AM 172.25.0.26 GET /vite.svg
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:20 AM 172.25.0.26 Returned 200 in 3 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:20 +0000] "GET /vite.svg HTTP/1.0" 200 460 "https://dev.pl-ai.it/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-image-generator-service-prod   | [15/Jul/2025 10:57:21] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-auth-service-prod              | [15/Jul/2025 10:57:22] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-chatbot-service-prod           | [15/Jul/2025 10:57:22] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:25 AM 172.25.0.26 GET /vite.svg
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:25 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:25 +0000] "GET /vite.svg HTTP/1.0" 200 460 "https://dev.pl-ai.it/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:29 AM 172.25.0.26 GET /login
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:29 AM 172.25.0.26 Returned 200 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:29 +0000] "GET /login HTTP/1.0" 200 460 "https://www.google.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 GET /assets/index-Ba6aqRrq.css
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 GET /assets/index-LksxMZE5.js
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:30 +0000] "GET /assets/index-Ba6aqRrq.css HTTP/1.0" 200 225246 "https://dev.pl-ai.it/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:30 +0000] "GET /assets/index-LksxMZE5.js HTTP/1.0" 200 2064929 "https://dev.pl-ai.it/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 GET /LogoFG.png
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 GET /golinelliAI.png
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 GET /G-LAB_logo.png
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:30 +0000] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486 "https://dev.pl-ai.it/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:57:30] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 Returned 304 in 4 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:30 +0000] "GET /LogoFG.png HTTP/1.0" 304 0 "https://dev.pl-ai.it/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:30 +0000] "GET /golinelliAI.png HTTP/1.0" 304 0 "https://dev.pl-ai.it/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 Returned 304 in 6 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:30 +0000] "GET /G-LAB_logo.png HTTP/1.0" 304 0 "https://dev.pl-ai.it/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 Returned 304 in 5 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 GET /assets/uicons-regular-rounded-J3WOUERV-0sU45oCT.woff2
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 Returned 200 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:30 +0000] "GET /assets/uicons-regular-rounded-J3WOUERV-0sU45oCT.woff2 HTTP/1.0" 200 385636 "https://dev.pl-ai.it/assets/index-Ba6aqRrq.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 GET /vite.svg
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:30 AM 172.25.0.26 Returned 200 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:30 +0000] "GET /vite.svg HTTP/1.0" 200 460 "https://dev.pl-ai.it/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:30 +0000] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62 "https://dev.pl-ai.it/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:57:30] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:39 AM 172.25.0.26 GET /auth/callback
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:39 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:39 +0000] "GET /auth/callback HTTP/1.0" 200 460 "https://accounts.google.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:39 AM 172.25.0.26 GET /assets/index-LksxMZE5.js
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:39 AM 172.25.0.26 Returned 304 in 1 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:39 AM 172.25.0.26 GET /assets/index-Ba6aqRrq.css
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:39 +0000] "GET /assets/index-LksxMZE5.js HTTP/1.0" 304 0 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:39 +0000] "GET /assets/index-Ba6aqRrq.css HTTP/1.0" 304 0 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:39 AM 172.25.0.26 Returned 304 in 2 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 GET /G-LAB_logo.png
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 GET /golinelliAI.png
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 GET /LogoFG.png
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:40 +0000] "GET /G-LAB_logo.png HTTP/1.0" 304 0 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 Returned 304 in 3 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:40 +0000] "GET /golinelliAI.png HTTP/1.0" 304 0 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 Returned 304 in 3 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:40 +0000] "GET /LogoFG.png HTTP/1.0" 304 0 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 Returned 304 in 4 ms
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 GET /assets/uicons-regular-rounded-J3WOUERV-0sU45oCT.woff2
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 Returned 304 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:40 +0000] "GET /assets/uicons-regular-rounded-J3WOUERV-0sU45oCT.woff2 HTTP/1.0" 304 0 "https://dev.pl-ai.it/assets/index-Ba6aqRrq.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:40 +0000] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:57:40] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:40 +0000] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:57:40] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 GET /vite.svg
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 Returned 200 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:40 +0000] "GET /vite.svg HTTP/1.0" 200 460 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:40 +0000] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:57:40] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 GET /vite.svg
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 Returned 200 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:40 +0000] "GET /vite.svg HTTP/1.0" 200 460 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:57:40] "POST /api/v1/social-auth/callback/ HTTP/1.0" 200 785
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:40 +0000] "POST /api/v1/social-auth/callback/ HTTP/1.0" 200 785 "https://dev.pl-ai.it/auth/callback" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 GET /vite.svg
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:40 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:40 +0000] "GET /vite.svg HTTP/1.0" 200 460 "https://dev.pl-ai.it/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:57:40] "GET /api/users/me/ HTTP/1.0" 400 16510
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:40 +0000] "GET /api/users/me/ HTTP/1.0" 400 16510 "https://dev.pl-ai.it/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:44 AM 172.25.0.26 GET /vite.svg
pl-ai-learning-service-prod          | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-learning-service-prod          | Traceback (most recent call last):
pl-ai-learning-service-prod          |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-learning-service-prod          |     response = get_response(request)
pl-ai-learning-service-prod          |                ^^^^^^^^^^^^^^^^^^^^^
pl-ai-learning-service-prod          |   File "/usr/local/lib/python3.11/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-learning-service-prod          |     response = self.process_request(request)
pl-ai-learning-service-prod          |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pl-ai-learning-service-prod          |   File "/usr/local/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-learning-service-prod          |     host = request.get_host()
pl-ai-learning-service-prod          |            ^^^^^^^^^^^^^^^^^^
pl-ai-learning-service-prod          |   File "/usr/local/lib/python3.11/site-packages/django/http/request.py", line 150, in get_host
pl-ai-learning-service-prod          |     raise DisallowedHost(msg)
pl-ai-learning-service-prod          | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:44 AM 172.25.0.26 Returned 200 in 3 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:44 +0000] "GET /vite.svg HTTP/1.0" 200 460 "https://dev.pl-ai.it/learning" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-learning-service-prod          | Bad Request: /api/lessons/
pl-ai-learning-service-prod          | "GET /api/lessons/ HTTP/1.0" 400 143
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:44 +0000] "GET /api/learning-service/lessons/ HTTP/1.0" 400 143 "https://dev.pl-ai.it/learning" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-classifier-db-prod             | 2025-07-15 10:57:45.713 UTC [27] LOG:  checkpoint starting: time
pl-ai-classifier-db-prod             | 2025-07-15 10:57:45.727 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.001 s, total=0.015 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
pl-ai-rag-db-prod                    | 2025-07-15 10:57:46.452 UTC [27] LOG:  checkpoint starting: time
pl-ai-analysis-db-prod               | 2025-07-15 10:57:46.733 UTC [26] LOG:  checkpoint starting: time
pl-ai-analysis-db-prod               | 2025-07-15 10:57:46.749 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.001 s, total=0.016 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:47 +0000] "GET /vite.svg HTTP/1.0" 200 460 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:47 AM 172.25.0.26 GET /vite.svg
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:57:47 AM 172.25.0.26 Returned 200 in 1 ms
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:57:47] "GET /api/users/me/preferences/ HTTP/1.0" 400 16561
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:47 +0000] "GET /api/users/me/preferences/ HTTP/1.0" 400 16561 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | [15/Jul/2025 10:57:47] "GET /api/users/me/ HTTP/1.0" 400 16513
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:47 +0000] "GET /api/users/me/ HTTP/1.0" 400 16513 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:57:47] "GET /api/users/me/ HTTP/1.0" 400 16513
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:47 +0000] "GET /api/users/me/ HTTP/1.0" 400 16513 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-db-prod                   | 2025-07-15 10:57:47.994 UTC [26] LOG:  checkpoint starting: time
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:48 +0000] "GET /api/users/me/ HTTP/1.0" 400 16513 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | [15/Jul/2025 10:57:48] "GET /api/users/me/ HTTP/1.0" 400 16513
pl-ai-user-service-prod              | [15/Jul/2025 10:57:48] "GET /api/users/me/preferences/ HTTP/1.0" 400 16561
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:57:48 +0000] "GET /api/users/me/preferences/ HTTP/1.0" 400 16561 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-db-prod                   | 2025-07-15 10:57:48.144 UTC [27] LOG:  checkpoint starting: time
pl-ai-user-db-prod                   | 2025-07-15 10:57:48.161 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.001 s, total=0.017 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
pl-ai-resource-db-prod               | 2025-07-15 10:57:48.313 UTC [26] LOG:  checkpoint starting: time
pl-ai-resource-db-prod               | 2025-07-15 10:57:48.329 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.001 s, total=0.018 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
pl-ai-learning-db-prod               | 2025-07-15 10:57:48.473 UTC [26] LOG:  checkpoint starting: time
pl-ai-learning-db-prod               | 2025-07-15 10:57:48.488 UTC [26] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.001 s, total=0.016 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
pl-ai-image-generator-db-prod        | 2025-07-15 10:57:48.551 UTC [27] LOG:  checkpoint starting: time
pl-ai-image-generator-db-prod        | 2025-07-15 10:57:48.569 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.001 s, total=0.019 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
pl-ai-chatbot-db-prod                | 2025-07-15 10:57:48.650 UTC [27] LOG:  checkpoint starting: time
pl-ai-chatbot-db-prod                | 2025-07-15 10:57:48.667 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.001 s, total=0.017 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
pl-ai-resource-manager-service-prod  | [15/Jul/2025 10:57:49] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-auth-db-prod                   | 2025-07-15 10:57:51.224 UTC [26] LOG:  checkpoint complete: wrote 35 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=3.220 s, sync=0.001 s, total=3.231 s; sync files=24, longest=0.001 s, average=0.001 s; distance=14 kB, estimate=14 kB
pl-ai-classifier-service-prod        | [15/Jul/2025 10:57:51] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-learning-service-prod          | "GET /admin/login/ HTTP/1.1" 200 4193
pl-ai-user-service-prod              | [15/Jul/2025 10:57:54] "GET /admin/login/ HTTP/1.1" 200 4178
pl-ai-data-analysis-service-prod     | [15/Jul/2025 10:57:54] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:03] "GET /api/users/me/ HTTP/1.0" 400 16513
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:03 +0000] "GET /api/users/me/ HTTP/1.0" 400 16513 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-rag-db-prod                    | 2025-07-15 10:58:03.218 UTC [27] LOG:  checkpoint complete: wrote 170 buffers (1.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=16.757 s, sync=0.004 s, total=16.767 s; sync files=157, longest=0.002 s, average=0.001 s; distance=890 kB, estimate=890 kB
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:03] "GET /api/users/me/preferences/ HTTP/1.0" 400 16561
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:03 +0000] "GET /api/users/me/preferences/ HTTP/1.0" 400 16561 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:03] "GET /api/users/me/ HTTP/1.0" 400 16513
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:03 +0000] "GET /api/users/me/ HTTP/1.0" 400 16513 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:03] "GET /api/users/me/ HTTP/1.0" 400 16513
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:03 +0000] "GET /api/users/me/ HTTP/1.0" 400 16513 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:03] "GET /api/users/me/preferences/ HTTP/1.0" 400 16561
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:03 +0000] "GET /api/users/me/preferences/ HTTP/1.0" 400 16561 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:15] "PATCH /api/users/me/ HTTP/1.0" 400 16563
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:15 +0000] "PATCH /api/users/me/ HTTP/1.0" 400 16563 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:18] "PUT /api/users/me/preferences/ HTTP/1.0" 400 16607
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:18 +0000] "PUT /api/users/me/preferences/ HTTP/1.0" 400 16607 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-image-generator-service-prod   | [15/Jul/2025 10:58:21] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-chatbot-service-prod           | [15/Jul/2025 10:58:22] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-auth-service-prod              | [15/Jul/2025 10:58:22] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:23] "PATCH /api/users/me/ HTTP/1.0" 400 16563
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:23 +0000] "PATCH /api/users/me/ HTTP/1.0" 400 16563 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:23] "PATCH /api/users/me/ HTTP/1.0" 400 16563
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:23 +0000] "PATCH /api/users/me/ HTTP/1.0" 400 16563 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:23] "PATCH /api/users/me/ HTTP/1.0" 400 16563
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:23 +0000] "PATCH /api/users/me/ HTTP/1.0" 400 16563 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:23] "PATCH /api/users/me/ HTTP/1.0" 400 16563
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:23 +0000] "PATCH /api/users/me/ HTTP/1.0" 400 16563 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:23] "PATCH /api/users/me/ HTTP/1.0" 400 16563
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:23 +0000] "PATCH /api/users/me/ HTTP/1.0" 400 16563 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:25 AM 172.25.0.26 GET /vite.svg
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:25 AM 172.25.0.26 Returned 200 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:25 +0000] "GET /vite.svg HTTP/1.0" 200 460 "https://dev.pl-ai.it/image-generator" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:26 AM 172.25.0.26 GET /vite.svg
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:26 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:26 +0000] "GET /vite.svg HTTP/1.0" 200 460 "https://dev.pl-ai.it/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:28 AM 172.25.0.26 GET /vite.svg
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:28 AM 172.25.0.26 Returned 200 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:28 +0000] "GET /vite.svg HTTP/1.0" 200 460 "https://dev.pl-ai.it/image-classifier" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-classifier-service-prod        | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-classifier-service-prod        | Traceback (most recent call last):
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-classifier-service-prod        |     response = get_response(request)
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-classifier-service-prod        |     response = self.process_request(request)
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-classifier-service-prod        |     host = request.get_host()
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-classifier-service-prod        |     raise DisallowedHost(msg)
pl-ai-classifier-service-prod        | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-classifier-service-prod        | [15/Jul/2025 10:58:28] "GET /api/classifier/models/ HTTP/1.0" 400 16131
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:28 +0000] "GET /api/classifier/models/ HTTP/1.0" 400 16131 "https://dev.pl-ai.it/image-classifier" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-classifier-service-prod        | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-classifier-service-prod        | Traceback (most recent call last):
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-classifier-service-prod        |     response = get_response(request)
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-classifier-service-prod        |     response = self.process_request(request)
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-classifier-service-prod        |     host = request.get_host()
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-classifier-service-prod        |     raise DisallowedHost(msg)
pl-ai-classifier-service-prod        | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-classifier-service-prod        | [15/Jul/2025 10:58:35] "GET /api/classifier/models/ HTTP/1.0" 400 16131
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:35 +0000] "GET /api/classifier/models/ HTTP/1.0" 400 16131 "https://dev.pl-ai.it/image-classifier" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-classifier-service-prod        | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-classifier-service-prod        | Traceback (most recent call last):
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-classifier-service-prod        |     response = get_response(request)
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-classifier-service-prod        |     response = self.process_request(request)
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-classifier-service-prod        |     host = request.get_host()
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-classifier-service-prod        |     raise DisallowedHost(msg)
pl-ai-classifier-service-prod        | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-classifier-service-prod        | [15/Jul/2025 10:58:35] "GET /api/classifier/models/ HTTP/1.0" 400 16131
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:35 +0000] "GET /api/classifier/models/ HTTP/1.0" 400 16131 "https://dev.pl-ai.it/image-classifier" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-classifier-service-prod        | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-classifier-service-prod        | Traceback (most recent call last):
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-classifier-service-prod        |     response = get_response(request)
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-classifier-service-prod        |     response = self.process_request(request)
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-classifier-service-prod        |     host = request.get_host()
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-classifier-service-prod        |     raise DisallowedHost(msg)
pl-ai-classifier-service-prod        | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-classifier-service-prod        | [15/Jul/2025 10:58:36] "GET /api/classifier/models/ HTTP/1.0" 400 16131
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:36 +0000] "GET /api/classifier/models/ HTTP/1.0" 400 16131 "https://dev.pl-ai.it/image-classifier" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:37] "PATCH /api/users/me/ HTTP/1.0" 400 16563
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:37 +0000] "PATCH /api/users/me/ HTTP/1.0" 400 16563 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:41 AM 172.25.0.26 GET /home
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:41 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:41 +0000] "GET /home HTTP/1.0" 200 460 "https://accounts.google.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:41 AM 172.25.0.26 GET /assets/index-LksxMZE5.js
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:41 AM 172.25.0.26 Returned 304 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:41 +0000] "GET /assets/index-LksxMZE5.js HTTP/1.0" 304 0 "https://dev.pl-ai.it/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:41 AM 172.25.0.26 GET /assets/index-Ba6aqRrq.css
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:41 +0000] "GET /assets/index-Ba6aqRrq.css HTTP/1.0" 304 0 "https://dev.pl-ai.it/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:41 AM 172.25.0.26 Returned 304 in 1 ms
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:42] "GET /api/users/me/ HTTP/1.0" 400 16510
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:42 +0000] "GET /api/users/me/ HTTP/1.0" 400 16510 "https://dev.pl-ai.it/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:58:42] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:42 +0000] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486 "https://dev.pl-ai.it/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:42 +0000] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62 "https://dev.pl-ai.it/home" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-auth-service-prod              | [15/Jul/2025 10:58:42] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:44] "GET /api/users/me/ HTTP/1.0" 400 16513
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:44 +0000] "GET /api/users/me/ HTTP/1.0" 400 16513 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:44] "GET /api/users/me/preferences/ HTTP/1.0" 400 16561
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:44 +0000] "GET /api/users/me/preferences/ HTTP/1.0" 400 16561 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:44] "GET /api/users/me/ HTTP/1.0" 400 16513
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:44 +0000] "GET /api/users/me/ HTTP/1.0" 400 16513 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | [15/Jul/2025 10:58:44] "GET /api/users/me/ HTTP/1.0" 400 16513
pl-ai-user-service-prod              | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-user-service-prod              | Traceback (most recent call last):
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-user-service-prod              |     response = get_response(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-user-service-prod              |     response = self.process_request(request)
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-user-service-prod              |     host = request.get_host()
pl-ai-user-service-prod              |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-user-service-prod              |     raise DisallowedHost(msg)
pl-ai-user-service-prod              | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:44 +0000] "GET /api/users/me/ HTTP/1.0" 400 16513 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | [15/Jul/2025 10:58:44] "GET /api/users/me/preferences/ HTTP/1.0" 400 16561
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:44 +0000] "GET /api/users/me/preferences/ HTTP/1.0" 400 16561 "https://dev.pl-ai.it/profile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:49 AM 172.25.0.26 GET /robots.txt
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:49 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:49 +0000] "GET /robots.txt HTTP/1.0" 200 460 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" "66.249.73.130"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:49 AM 172.25.0.26 GET /
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:58:49 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:49 +0000] "GET / HTTP/1.0" 200 460 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.7151.103 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" "66.249.73.131"
pl-ai-resource-manager-service-prod  | [15/Jul/2025 10:58:50] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-classifier-service-prod        | [15/Jul/2025 10:58:51] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-learning-service-prod          | "GET /admin/login/ HTTP/1.1" 200 4193
pl-ai-resource-manager-service-prod  | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-resource-manager-service-prod  | Traceback (most recent call last):
pl-ai-resource-manager-service-prod  |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-resource-manager-service-prod  |     response = get_response(request)
pl-ai-resource-manager-service-prod  |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-resource-manager-service-prod  |     response = self.process_request(request)
pl-ai-resource-manager-service-prod  |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-resource-manager-service-prod  |     host = request.get_host()
pl-ai-resource-manager-service-prod  |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-resource-manager-service-prod  |     raise DisallowedHost(msg)
pl-ai-resource-manager-service-prod  | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-resource-manager-service-prod  | [15/Jul/2025 10:58:53] "GET /api/ HTTP/1.0" 400 16603
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:53 +0000] "GET /api/resources/ HTTP/1.0" 400 16603 "https://dev.pl-ai.it/resources" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-resource-manager-service-prod  | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-resource-manager-service-prod  | Traceback (most recent call last):
pl-ai-resource-manager-service-prod  |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-resource-manager-service-prod  |     response = get_response(request)
pl-ai-resource-manager-service-prod  |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-resource-manager-service-prod  |     response = self.process_request(request)
pl-ai-resource-manager-service-prod  |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-resource-manager-service-prod  |     host = request.get_host()
pl-ai-resource-manager-service-prod  |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-resource-manager-service-prod  |     raise DisallowedHost(msg)
pl-ai-resource-manager-service-prod  | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-resource-manager-service-prod  | [15/Jul/2025 10:58:53] "GET /api/storage-info/ HTTP/1.0" 400 16659
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:58:53 +0000] "GET /api/resources/storage-info/ HTTP/1.0" 400 16659 "https://dev.pl-ai.it/resources" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36" "188.209.85.242"
pl-ai-user-service-prod              | [15/Jul/2025 10:58:54] "GET /admin/login/ HTTP/1.1" 200 4178
pl-ai-data-analysis-service-prod     | [15/Jul/2025 10:58:54] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-nginx-prod                     | 2025/07/15 10:58:57 [warn] 20#20: *213 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 172.24.0.1, server: localhost, request: "POST /api/classifier/train/ HTTP/1.0", host: "dev.pl-ai.it", referrer: "https://dev.pl-ai.it/image-classifier"
pl-ai-classifier-service-prod        | Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-classifier-service-prod        | Traceback (most recent call last):
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
pl-ai-classifier-service-prod        |     response = get_response(request)
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
pl-ai-classifier-service-prod        |     response = self.process_request(request)
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
pl-ai-classifier-service-prod        |     host = request.get_host()
pl-ai-classifier-service-prod        |   File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 150, in get_host
pl-ai-classifier-service-prod        |     raise DisallowedHost(msg)
pl-ai-classifier-service-prod        | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'dev.pl-ai.it'. You may need to add 'dev.pl-ai.it' to ALLOWED_HOSTS.
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:59:01 AM 172.25.0.26 GET /assets/index-Ba6aqRrq.css
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:59:01 AM 172.25.0.26 Returned 200 in 1 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:59:02 +0000] "GET /assets/index-Ba6aqRrq.css HTTP/1.0" 200 225246 "https://www.appzapp.net/" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.7151.119 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" "66.249.73.132"
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:59:02 AM 172.25.0.26 GET /assets/index-LksxMZE5.js
pl-ai-frontend-prod                  |  HTTP  7/15/2025 10:59:02 AM 172.25.0.26 Returned 200 in 2 ms
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:59:02 +0000] "GET /assets/index-LksxMZE5.js HTTP/1.0" 200 2064929 "https://www.appzapp.net/" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.7151.119 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" "66.249.73.130"
pl-ai-auth-service-prod              | [15/Jul/2025 10:59:06] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:59:06 +0000] "GET /api/v1/social-auth/config/ HTTP/1.0" 200 486 "https://www.appzapp.net/" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.7151.119 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" "66.249.73.131"
pl-ai-auth-service-prod              | [15/Jul/2025 10:59:06] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62
pl-ai-nginx-prod                     | 172.24.0.1 - - [15/Jul/2025:10:59:06 +0000] "GET /api/v1/social-auth/providers/ HTTP/1.0" 200 62 "https://www.appzapp.net/" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.7151.119 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" "66.249.73.131"
pl-ai-image-generator-service-prod   | [15/Jul/2025 10:59:21] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-chatbot-service-prod           | [15/Jul/2025 10:59:22] "GET /admin/login/ HTTP/1.1" 200 4168
pl-ai-auth-service-prod              | [15/Jul/2025 10:59:22] "GET /admin/login/ HTTP/1.1" 200 4168
